name: Deploy-Production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant Permissions to executables
        run: chmod -R +rwx ./scripts

      - name: Build the Docker image
        env:
          IMAGE_STORAGE: vyacheslavborovsky/covid-dashboard-docker-repo
          TAG: latest
        run: sh ./scripts/build-image.sh $IMAGE_STORAGE $TAG

      - name: Push the Docker image to Docker Hub
        env:
          IMAGE_STORAGE: vyacheslavborovsky/covid-dashboard-docker-repo
          TAG: latest
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: sh ./scripts/push-image.sh $IMAGE_STORAGE $TAG

      - name: Deploy to Heroku
        env:
          IMAGE_STORAGE: vyacheslavborovsky/covid-dashboard-docker-repo
          TAG: latest
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: sh ./scripts/deploy-heroku.sh
